/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Library {

	public boolean someLibraryMethod() {
		return false;
	}

	public String otroTest() {
		return "Hola";
	}

	public static void main(String[] args) {

		int a = 4;
		int b = 6;

		System.out.println(a + b);

	}

}
